---
categorical_dropdown:
  label: Categorical Variable
  dropdown_list:
    - 
      label: Country
      value: site_country
    - 
      label: Region
      value: site_region
    - 
      label: State or Province
      value: site_state_province
    - 
      label: Climate Zone
      value: site_clim_zone
    - 
      label: Project Type
      value: bldg_proj_type
    - 
      label: IBC Construction Type
      value: bldg_ibc_type
    - 
      label: Attached Parking Type
      value: bldg_park_type
    - 
      label: Primary Building Use Type
      value: bldg_prim_use
    - 
      label: Secondary Building Use Type
      value: bldg_sec_use
    - 
      label: Stories Above Grade
      value: bldg_stories_above
    - 
      label: Stories Below Grade
      value: bldg_stories_below
    - 
      label: Building Height
      value: bldg_height
    - 
      label: Seismic Site Class
      value: str_seis_site_cls
    - 
      label: Seismic Design Category
      value: str_sdc
    - 
      label: Primary Horizontal Gravity System
      value: str_prim_horiz_sys
    - 
      label: Primary Vertical Gravity System
      value: str_prim_vert_sys
    - 
      label: Primary Lateral Force Resisting System
      value: str_lat_sys
    - 
      label: Podium
      value: str_podium
    - 
      label: Foundation Type
      value: str_fdn_type
    - 
      label: Structural System Summary
      value: str_sys_summary
    - 
      label: Design Phase
      value: lca_design_phase
    - 
      label: Software
      value: lca_software
    - 
      label: Purpose of Assessment
      value: lca_purp_of_assessment
    - 
      label: Physical Scope Summary
      value: lca_phys_scope
    - 
      label: Embodied Carbon Reductions
      value: lca_ec_reductions
  first_item: site_state_province
  dropdown_id: categorical_dropdown

continuous_dropdown:
  label: Continuous Variable
  dropdown_list:
    - 
      label: Constructed Floor Area
      value: bldg_cfa
    - 
      label: Gross Floor Area
      value: bldg_gfa
    - 
      label: Parking Floor Area
      value: bldg_park_gfa
    - 
      label: Added Floor Area
      value: bldg_added_gfa
    - 
      label: Renovated Floor Area
      value: bldg_renovated_gfa
    - 
      label: Occupants
      value: bldg_occupants
    - 
      label: Residential Units
      value: bldg_res_units
    - 
      label: Thermal Envelope Area
      value: bldg_therm_env_area
    - 
      label: Window-to-Wall Ratio
      value: bldg_wwr
    - 
      label: Average R-Value of Walls
      value: bldg_rval_walls
    - 
      label: Average R-Value of Roofs
      value: bldg_rval_roofs
    - 
      label: Ultimate Wind Speed
      value: str_wind_speed
    - 
      label: Typical Column Grid, Long Direction
      value: str_grid_long
    - 
      label: Typical Column Grid, Short Direction
      value: str_grid_short
    - 
      label: Embodied Carbon Reduction Percentage
      value: lca_ec_reduction_percent
  first_item: bldg_cfa
  dropdown_id: continuous_dropdown

total_impact_dropdown: 
  label: Impacts
  dropdown_list: 
    - 
      label: Embodied Carbon Intensity
      value: eci_a_to_c_gfa
    -  
      label: Eutrophication Potential Intensity
      value: epi_a_to_c_gfa
    -  
      label: Acidification Potential Intensity
      value: api_a_to_c_gfa
    -  
      label: Smog Formation Potential Intensity
      value: sfpi_a_to_c_gfa
    -  
      label: Ozone Depletion Potential Intensity
      value: odpi_a_to_c_gfa
    -  
      label: Natural Resource Depletion Intensity
      value: nredi_a_to_c_gfa
    -  
      label: Embodied Carbon per Occupant
      value: ec_per_occupant_a_to_c
    -  
      label: Embodied Carbon per Residential Unit
      value: ec_per_res_unit_a_to_c
  first_item: eci_a_to_c
  dropdown_id: total_impact_dropdown

color_dropdown:
  label: Color
  dropdown_list:
    - label: No color
      value: No color
    - 
      label: Country
      value: site_country
    - 
      label: Region
      value: site_region
    - 
      label: State or Province
      value: site_state_province
    - 
      label: Climate Zone
      value: site_clim_zone
    - 
      label: Project Type
      value: bldg_proj_type
    - 
      label: IBC Construction Type
      value: bldg_ibc_type
    - 
      label: Attached Parking Type
      value: bldg_park_type
    - 
      label: Primary Building Use Type
      value: bldg_prim_use
    - 
      label: Secondary Building Use Type
      value: bldg_sec_use
    - 
      label: Stories Above Grade
      value: bldg_stories_above
    - 
      label: Stories Below Grade
      value: bldg_stories_below
    - 
      label: Building Height
      value: bldg_height
    - 
      label: Seismic Site Class
      value: str_seis_site_cls
    - 
      label: Seismic Design Category
      value: str_sdc
    - 
      label: Primary Horizontal Gravity System
      value: str_prim_horiz_sys
    - 
      label: Primary Vertical Gravity System
      value: str_prim_vert_sys
    - 
      label: Primary Lateral Force Resisting System
      value: str_lat_sys
    - 
      label: Podium
      value: str_podium
    - 
      label: Foundation Type
      value: str_fdn_type
    - 
      label: Structural System Summary
      value: str_sys_summary
    - 
      label: Design Phase
      value: lca_design_phase
    - 
      label: Software
      value: lca_software
    - 
      label: Purpose of Assessment
      value: lca_purp_of_assessment
    - 
      label: Physical Scope Summary
      value: lca_phys_scope
    - 
      label: Embodied Carbon Reductions
      value: lca_ec_reductions
  first_item: No color
  dropdown_id: color_dropdown

log_linear_dropdown:
  label: Log-Linear
  dropdown_list:
    - Linear
    - Logarithmic
  first_item: Linear
  dropdown_id: log_linear_dropdown

field_name_map:
  site_country: Country
  site_region: Region
  site_state_province: State or Province
  site_clim_zone: Climate Zone
  bldg_proj_type: Project Type
  bldg_ibc_type: IBC Construction Type
  bldg_park_type: Attached Parking Type
  bldg_prim_use: Primary Building Use Type
  bldg_sec_use: Secondary Building Use Type
  bldg_stories_above: Stories Above Grade
  bldg_stories_below: Stories Below Grade
  bldg_height: Building Height
  str_seis_site_cls: Seismic Site Class
  str_sdc: Seismic Design Category
  str_prim_horiz_sys: Primary Horizontal Gravity System
  str_prim_vert_sys: Primary Vertical Gravity System
  str_lat_sys: Primary Lateral Force Resisting System
  str_podium: Podium
  str_fdn_type: Foundation Type
  str_sys_summary: Structural System Summary
  lca_design_phase: Design Phase
  lca_software: Software
  lca_purp_of_assessment: Purpose of Assessment
  lca_phys_scope: Physical Scope Summary
  lca_ec_reductions: Embodied Carbon Reductions
  eci_a_to_c_gfa: Embodied Carbon Intensity
  epi_a_to_c_gfa: Eutrophication Potential Intensity
  api_a_to_c_gfa: Acidification Potential Intensity
  sfpi_a_to_c_gfa: Smog Formation Potential Intensity
  odpi_a_to_c_gfa: Ozone Depletion Potential Intensity
  nredi_a_to_c_gfa: Natural Resource Depletion Intensity
  ec_per_occupant_a_to_c: Embodied Carbon per Occupant
  ec_per_res_unit_a_to_c: Embodied Carbon per Residential Unit
  bldg_cfa: Constructed Floor Area
  bldg_gfa: Gross Floor Area
  bldg_park_gfa: Parking Floor Area
  bldg_added_gfa: Added Floor Area
  bldg_renovated_gfa: Renovated Floor Area
  bldg_occupants: Occupants
  bldg_res_units: Residential Units
  bldg_therm_env_area: Thermal Envelope Area
  bldg_wwr: Window-to-Wall Ratio
  bldg_rval_walls: Average R-Value of Walls
  bldg_rval_roofs: Average R-Value of Roofs
  str_wind_speed: Ultimate Wind Speed
  str_grid_long: Typical Column Grid, Long Direction
  str_grid_short: Typical Column Grid, Short Direction
  lca_ec_reduction_percent: Embodied Carbon Reduction Percentage
