---
categorical_dropdown:
  label: Categorical Variable
  dropdown_list:
    - site_country
    - site_region
    - site_state_province
    - site_clim_zone
    - bldg_proj_type
    - bldg_ibc_type
    - bldg_park_type
    - bldg_prim_use
    - bldg_sec_use
    - bldg_stories_above
    - bldg_stories_below
    - bldg_height
    - str_seis_site_cls
    - str_sdc
    - str_prim_horiz_sys
    - str_prim_vert_sys
    - str_lat_sys
    - str_podium
    - str_fdn_type
    - str_sys_summary
    - lca_design_phase
    - lca_software
    - lca_purp_of_assessment
    - lca_phys_scope
    - lca_ec_reductions
  first_item: site_state_province
  dropdown_id: categorical_dropdown

continuous_dropdown:
  label: Continuous Variable
  dropdown_list:
    - bldg_cfa
    - bldg_gfa
    - bldg_park_gfa
    - bldg_added_gfa
    - bldg_renovated_gfa
    - bldg_occupants
    - bldg_res_units
    - bldg_therm_env_area
    - bldg_wwr
    - bldg_rval_walls
    - bldg_rval_roofs
    - str_wind_speed
    - str_grid_long
    - str_grid_short
    - lca_ec_reduction_percent
  first_item: bldg_cfa
  dropdown_id: continuous_dropdown

total_impact_dropdown: 
  label: Impacts
  dropdown_list: 
    - eci_a_to_c
    - epi_a_to_c
    - api_a_to_c
    - sfpi_a_to_c
    - odpi_a_to_c
    - nredi_a_to_c
    - ec_per_occupant_a_to_c
    - ec_per_res_unit_a_to_c
  first_item: eci_a_to_c
  dropdown_id: total_impact_dropdown

color_dropdown:
  label: Color
  dropdown_list:
    - No color
    - site_country
    - site_region
    - site_state_province
    - site_clim_zone
    - bldg_proj_type
    - bldg_ibc_type
    - bldg_park_type
    - bldg_prim_use
    - bldg_sec_use
    - bldg_stories_above
    - bldg_stories_below
    - bldg_height
    - str_seis_site_cls
    - str_sdc
    - str_prim_horiz_sys
    - str_prim_vert_sys
    - str_lat_sys
    - str_podium
    - str_fdn_type
    - str_sys_summary
    - lca_design_phase
    - lca_software
    - lca_purp_of_assessment
    - lca_phys_scope
    - lca_ec_reductions
  first_item: No color
  dropdown_id: color_dropdown

log_linear_dropdown:
  label: Log-Linear
  dropdown_list:
    - Linear
    - Logarithmic
  first_item: Linear
  dropdown_id: log_linear_dropdown

impact_type_dropdown:
  label: "Impact by:"
  dropdown_list:
    - Life Cycle Stage
    - OmniClass
  first_item: Life Cycle Stage
  dropdown_id: impact_type_dropdown

parallel_coord_checklist:
  label: "Dimensions"
  options:
    - 
      label: bldg_height
      value: bldg_height
    - 
      label: gfa_w_park_imp
      value: gfa_w_park_imp
    - 
      label: col_grid_long
      value: col_grid_long
    - 
      label: occupancy
      value: occupancy
    - 
      label: wind_speed
      value: wind_speed
    - 
      label: gfa_park_ratio
      value: gfa_park_ratio
  value:
    - bldg_height
    - gfa_w_park_imp
    - col_grid_long
  id: 'parallel_coord_checklist'
  order:
    - bldg_height
    - gfa_w_park_imp
    - col_grid_long
    - occupancy
    - wind_speed
    - gfa_park_ratio


